receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    send_batch_size: 1024
    timeout: 5s
  memory_limiter:
    check_interval: 1s
    limit_mib: 512
    spike_limit_mib: 128
  resource:
    attributes:
      - key: collector.source
        value: "otel-collector-central"
        action: upsert

exporters:
  prometheusremotewrite:
    endpoint: "http://prometheus:9090/api/v1/write"
    resource_to_telemetry_settings:
      enabled: true
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
    default_labels_enabled:
      exporter: false
  otlp/jaeger:
    endpoint: "jaeger:4317"
    tls:
      insecure: true
  debug:
    verbosity: basic

connectors:
  spanmetrics:
    dimensions:
      - name: http.method
      - name: http.status_code
      - name: rpc.grpc.status_code
    aggregation_temporality: "CUMULATIVE"
    metric_conflict_resolution: "rename"

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [prometheusremotewrite, debug]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [loki, debug]
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [spanmetrics, otlp/jaeger, debug]
    metrics/spanmetrics:
      receivers: [spanmetrics]
      processors: [memory_limiter, batch]
      exporters: [prometheusremotewrite]